
x-web: &x-web
  build: .
  restart: always
  environment:
    DJANGO_SETTINGS_MODULE: chat_analyser.settings
  depends_on:
    redis:
      condition: service_healthy
  

services:
  web:
    <<: *x-web
    ports:
      - "8000:8000"
    command: /app/start/web
  

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  celery_worker:
    <<: *x-web
    command: /app/start/celery/worker


volumes:
  redis_data:
