# Generated by Django 6.0.4 on 2026-05-06 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='openai', max_length=255)),
                ('model', models.CharField(blank=True, default='gpt-4o-mini', max_length=255)),
                ('chat_history_fraction', models.FloatField(default=0.4)),
                ('summarised_history_fraction', models.FloatField(default=0.2)),
                ('relevant_chat_history_fraction', models.FloatField(default=0.1)),
                ('memory_fraction', models.FloatField(default=0.2)),
                ('rag_fraction', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
