# Generated by Django 6.0.4 on 2026-05-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='model_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
