# Generated by Django 5.2.13 on 2026-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_tooluse'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
