# Generated by Django 5.2.13 on 2026-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_add_model_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
