# Generated by Django 5.2.13 on 2026-05-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_add_content_to_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='content',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='hash',
        ),
        migrations.AddField(
            model_name='memory',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
