# Generated by Django 5.2.13 on 2026-05-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_replace_memory_fields_with_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='ai.conversation'),
        ),
        migrations.AddField(
            model_name='memory',
            name='fetched_why',
            field=models.CharField(blank=True, choices=[('chat_summary', 'Chat Summary'), ('chat_relevant_history', 'Chat Relevant History'), ('relevant_memory', 'Relevant Memory'), ('other', 'Other')], default='', max_length=100, null=True),
        ),
    ]
