# Generated by Django 5.2.13 on 2026-05-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_memory_conversation_memory_fetched_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='responding_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='ai.message'),
        ),
    ]
