# Generated by Django 6.0.4 on 2026-05-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_conversation_agent_message_agent_config_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField()),
                ('messages', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_prompt', to='ai.message')),
            ],
        ),
    ]
