# Generated by Django 6.0.4 on 2026-06-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_ragdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragdocument',
            name='chunk_ids',
            field=models.JSONField(default=list),
        ),
    ]
